language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
  - pip install tox-travis python-coveralls

addons:
    apt:
       packages:
           - enchant
           - myspell-nl
           - myspell-fr
           - aspell-en

script:
  - tox

after_success:
    coveralls
